### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by Tajeeomstvo** [techreagan/youtube-clone-nodejs-api#4]
![image](https://user-images.githubusercontent.com/82711008/115471239-a6171980-a205-11eb-9cf1-57c7a9be03bf.png)

**Comment by JesseInvent** [comment]
Which means the server is up and running on port 3001, l will suggest you use an app like Postman for API testing

**Comment by techreagan** [comment]
@JesseInvent exactly. 

@Tajeeomstvo pull the frontend code. It's built with VueJs.
